Example 1: 

Insert a Single Row into MySQL Table from Python

In the below example, we will Insert a Single Row into a MySQL Table from Python.

Create a file named insertsinglerecord.py, and add the following code:

In [ ]:
# Importing the MySQL connector module and assigning it a short alias
import mysql.connector as mydbconnection

# Importing the Error class from the mysql.connector module for handling exceptions
from mysql.connector import Error

# Using try-except-finally block to handle database operations safely
try:
    # Establishing a connection to the MySQL database using the connect() method
    # Providing required parameters: database name, username, password, and port
    conn = mydbconnection.connect(
        database='usersdb',  # Name of the database to connect to
        user='root',         # Username to authenticate with
        password='password', # Password for the user
        port='3306'          # Port number where MySQL server is running (default is 3306)
    )

    # Defining an SQL INSERT query as a multi-line string
    # This query will insert a new row into the 'Laptop' table
    mySql_insert_query = """
    INSERT INTO Laptop (Id, Name, Price, Purchase_date) 
    VALUES 
    (15, 'Lenovo ThinkPad P71', 6459, '2019-08-14')
    """

    # Creating a cursor object using the connection
    # Cursor is used to execute SQL statements
    cursor = conn.cursor()

    # Executing the INSERT query using the cursor
    cursor.execute(mySql_insert_query)

    # Committing the transaction to make the change permanent in the database
    conn.commit()

    # Printing how many rows were inserted (should be 1 in this case)
    print(cursor.rowcount, "Record inserted successfully into Laptop table")

    # Closing the cursor after the operation is done
    cursor.close()

# Catching any exceptions related to MySQL using the Error class
except Error as e:
    # Printing the error message if any exception occurs
    print("Failed to insert record into Laptop table {}".format(e))  # fixed: should be 'e' not 'error'

# This block will run no matter what (either after try or except block)
finally:
    # Checking if the connection is still open
    if conn.is_connected():
        # Closing the database connection
        conn.close()
        # Confirming that the connection is closed
        print("MySQL connection is closed")

Example 2: Use Python Variables in a MySQL Insert Query

Sometimes, you need to insert a Python variable value into a table’s column. For example, in the user signup form, the user enters his/her details. You can take those values in Python variables and insert them into a table.

We can insert Python variables into the table using the prepared statement and parameterized query.

Using a parameterized query, we can pass Python variables as a query parameter in which placeholders (%s) are used for parameters.

In [ ]:
# Importing the MySQL connector module with an alias for easier reference
import mysql.connector as mydbconnection

# Importing the Error class to handle any exceptions related to MySQL operations
from mysql.connector import Error

# Defining a function that inserts a record into the Laptop table
# The function accepts four arguments: id, name, price, and purchase_date
def insert_varibles_into_table(id, name, price, purchase_date):
    try:
        # Attempting to establish a connection to the MySQL database
        conn = mydbconnection.connect(
            database='usersdb',   # Name of the database to connect to
            user='root',          # MySQL username
            password='password',  # Password for the user
            port='3306'           # Port number for the MySQL server
        )

        # Creating a cursor object using the connection
        # Cursor allows us to execute SQL queries
        cursor = conn.cursor()

        # Defining the SQL INSERT query using placeholders (%s) for parameterized input
        # This helps prevent SQL injection and allows dynamic values
        mySql_insert_query = """
        INSERT INTO Laptop (Id, Name, Price, Purchase_date)
        VALUES (%s, %s, %s, %s)
        """                  

        # Grouping the input values into a tuple called 'record'
        record = (id, name, price, purchase_date)

        # Executing the query with the record values, replacing the %s placeholders
        cursor.execute(mySql_insert_query, record)

        # Committing the transaction to save changes to the database
        conn.commit()

        # Informing the user that the insertion was successful
        print("Record inserted successfully into Laptop table")

    # Handling any exceptions that occur during the process
    except Error as error:
        # Printing a user-friendly error message
        print("Failed to insert into MySQL table {}".format(error))

    # This block will run whether or not an exception occurred
    finally:
        # Checking if the connection is still open before attempting to close it
        if conn.is_connected():
            # Closing the cursor object to free up resources
            cursor.close()

            # Closing the database connection
            conn.close()

            # Printing confirmation that the connection has been closed
            print("MySQL connection is closed")

# Calling the function twice with different sets of values to insert two records
insert_varibles_into_table(2, 'Area 51M', 6999, '2019-04-14')
insert_varibles_into_table(3, 'MacBook Pro', 2499, '2019-06-20')

Example 3: 
Insert multiple rows into MySQL Table using cursor’s executemany()

In the previous example, we have used the execute() method of the cursor object to insert a single record.

What if you want to insert multiple rows into a table in a single insert query from the Python application. Use the cursor’s executemany() function to insert multiple records into a table.

Syntax of the executemany() method:
cursor.executemany(operation, seq_of_params)

This method executes Insert operation against all parameter sequences in the sequence seq_of_params argument.

You need to include lists of tuples in the seq_of_params argument along with the insert query.
Each tuple inside the list contains a single row that you want to insert so that you can add as many rows in the list and pass a list to a cursor.executemany() function along with the insert query.
Note: Each tuple is enclosed within parentheses and is separated by commas. For example, to insert multiple rows in a laptop table, we can use the following SQL Query:
INSERT INTO Laptop (Id, Name, Price, Purchase_date) VALUES (%s, %s, %s, %s)
And in seq_of_params, we are passing the below List.
records_to_insert = [(4, 'HP Pavilion Power', 1999, '2019-01-11'),
(5, 'MSI WS75 9TL-496', 5799, '2019-02-27'),
(6, 'Microsoft Surface', 2330, '2019-07-23')]

Create a file named insert_multipleRecords.py. Add the following code:

In [ ]:
# Importing the MySQL connector library and assigning it an alias for convenience
import mysql.connector as mydbconnection

# Importing the Error class from the MySQL connector to handle any database-related exceptions
from mysql.connector import Error

# Starting a try block to attempt database operations and catch errors if they occur
try:
    # Establishing a connection to the MySQL database using the given parameters
    conn = mydbconnection.connect(
        database='usersdb',    # Name of the database to use
        user='root',           # Username for connecting to the database
        password='password',   # Password associated with the user
        port='3306'            # Port on which MySQL is running (3306 is default)
    )

    # Writing the SQL INSERT query with placeholders (%s) for parameters
    # This query will be used to insert multiple records
    mySql_insert_query = """
    INSERT INTO Laptop (Id, Name, Price, Purchase_date) 
    VALUES (%s, %s, %s, %s)
    """

    # Creating a list of tuples, each representing one row of data to insert
    # These are the multiple records that will be inserted in a single batch
    records_to_insert = [
        (4, 'HP Pavilion Power', 1999, '2019-01-11'),
        (5, 'MSI WS75 9TL-496', 5799, '2019-02-27'),
        (6, 'Microsoft Surface', 2330, '2019-07-23')
    ]

    # Creating a cursor object that allows us to execute SQL statements
    cursor = conn.cursor()

    # Executing the insert query for all records in the list at once
    # executemany() is used for batch insertion of multiple rows
    cursor.executemany(mySql_insert_query, records_to_insert)

    # Committing the transaction to make the changes permanent in the database
    conn.commit()

    # Printing how many rows were inserted (should be 3 in this case)
    print(cursor.rowcount, "Record inserted successfully into Laptop table")

# Handling any errors that occur during the execution of the try block
except Error as error:
    # Printing a message along with the actual error encountered
    print("Failed to insert record into MySQL table {}".format(error))

# The finally block will always run, regardless of whether an exception was thrown
finally:
    # Checking if the connection is still open before closing it
    if conn.is_connected():
        # Closing the cursor to release database resources
        cursor.close()

        # Closing the connection to the database
        conn.close()

        # Printing a message to confirm the connection has been closed
        print("MySQL connection is closed")